package com.example.pmpm_tarea2_ijg;

import java.util.ArrayList;
import java.util.List;


public class Datos {

   static List<Personaje> datos = new ArrayList<>();

   static {
    datos.add(new Personaje(R.drawable.mario, "Es el protagonista de la serie de Super Mario. Es un fontanero valiente y de buen corazón, con su característico gorro rojo y bigote. Siempre está dispuesto a salvar el Reino Champiñón de las garras del malvado Bowser. Es conocido por su valentía y agilidad. Aunque es de estatura pequeña, su gran espíritu lo convierte en un héroe inquebrantable.", "Mario Bros","Super Salto"));
    datos.add(new Personaje(R.drawable.luigi, "Luigi es el hermano menor de Mario, también es un fontanero valiente, aunque es más alto y delgado. A menudo vive a la sombra de su hermano mayor, pero ha demostrado ser un héroe por derecho propio. De naturaleza un poco más tímida, Luigi tiene un gran corazón y siempre está dispuesto a ayudar, incluso si se siente inseguro o nervioso. Es conocido por su gorro verde y su lealtad hacia Mario.", "Luigi Bros","Salto Súper Largo"));
    datos.add(new Personaje(R.drawable.peach, "La Princesa Peach es la gobernante del Reino Champiñón y una de las figuras más importantes de la serie Super Mario. Con su vestido rosa, corona dorada y personalidad amable, es conocida por ser elegante, valiente y decidida. Aunque a menudo es secuestrada por Bowser, también ha demostrado ser una heroína fuerte y capaz.", "Peach","Flotar en el aire"));
    datos.add(new Personaje(R.drawable.toad, " Toad es uno de los habitantes del Reino Champiñón y fiel servidor de la Princesa Peach. Es pequeño, con una cabeza en forma de champiñón de colores rojo y blanco, y lleva un chaleco azul y pantalones cortos. Aunque puede parecer débil por su tamaño, Toad es valiente y siempre está dispuesto a ayudar en las aventuras de Mario y Peach. Su lealtad y energía lo hacen un aliado confiable", "Toad","Velocidad"));
    datos.add(new Personaje(R.drawable.bowser, "Bowser, también conocido como Rey Koopa, es el principal antagonista. Es un gran y feroz monstruo con rasgos de tortuga y dragón, caracterizado por su caparazón con púas y su aliento de fuego. A menudo secuestra a la Princesa Peach en un intento de conquistar el Reino Champiñón. Aunque es malvado y poderoso, a veces muestra un lado más cómico en sus interacciones con Mario y sus amigos.", "Bowser","Aliento de fuego"));
    datos.add(new Personaje(R.drawable.yoshi, "Yoshi es un dinosaurio amigable y fiel aliado de Mario. Con su característico color verde (aunque también puede ser de otros colores), su larga lengua y su capacidad para poner huevos, Yoshi es uno de los personajes más queridos de la serie. Vive en la Isla Yoshi y ha acompañado a Mario en numerosas aventuras, sirviendo como su montura y amigo inseparable.", "Yoshi","Lengua extensible"));
    datos.add(new Personaje(R.drawable.daisy, " Daisy es la princesa del Reino Sarasaland, y es conocida por su carácter enérgico, alegre y competitivo. Lleva un vestido amarillo con detalles naranjas y una corona con joyas verdes. Daisy se diferencia por su actitud más extrovertida y deportiva. Es amiga cercana de Peach y aparece frecuentemente en juegos de deportes, carreras y fiestas junto a los demás personajes del universo Mario.", "Daisy","Velocidad y agilidad"));
    datos.add(new Personaje(R.drawable.wario, "Wario es un personaje robusto, codicioso y algo malhumorado, conocido por ser el rival de Mario. Lleva un gorro y ropa de color amarillo y morado, y tiene un gran bigote que lo caracteriza. Aunque es un personaje egoísta y a menudo villanesco, también protagoniza sus propios juegos, como la serie WarioWare. A diferencia de Mario, Wario está más motivado por la búsqueda de riquezas y poder, lo que lo lleva a protagonizar situaciones cómicas y extravagantes.", "Wario","Fuerza"));
    datos.add(new Personaje(R.drawable.waluigi, "Waluigi es el compañero y contraparte de Wario, siendo alto, delgado y un poco torpe. Es el rival directo de Luigi y aparece principalmente en juegos de deportes, carreras y fiestas. Lleva un atuendo púrpura con un gorro que tiene una \"L\" al revés, y tiene un largo bigote puntiagudo. Waluigi es conocido por su actitud sarcástica, malhumorada y tramposa, a menudo jugando sucio para ganar, pero también por sus momentos cómicos y extravagantes.", "Waluigi","Habilidad para hacer trampas"));
    datos.add(new Personaje(R.drawable.rosalina, "Rosalina es la misteriosa y elegante princesa del universo de Mario, asociada con las estrellas y el espacio. Apareció por primera vez en Super Mario Galaxy como una figura central que cuida a los Lumas, pequeñas criaturas estelares. Tiene una larga cabellera rubia y viste un hermoso vestido azul claro. Su personalidad es calmada y sabia, y se la ve como una protectora de los cielos y las galaxias.", "Rosalina","Manipular las estrellas"));
    datos.add(new Personaje(R.drawable.bowser_jr, " Bowser Jr. es el hijo de Bowser y uno de los antagonistas recurrentes en la serie de Super Mario. Con su aspecto de pequeño koopa, lleva una máscara de pintura que puede usar para disfrazarse y un caparazón verde con púas. Aunque a menudo sigue los pasos de su padre y participa en los intentos de secuestrar a la Princesa Peach, también muestra un lado más juguetón y travieso, reflejando su juventud e inmadurez.", "Bowser JR","Pincel Mágico"));
    datos.add(new Personaje(R.drawable.boo, "Boo es un fantasma icónico de la serie Super Mario, conocido por su apariencia redonda, su color blanco y su expresión traviesa. Tiene grandes ojos y una boca sonriente, y se caracteriza por su timidez; cuando es mirado directamente, se esconde y se vuelve invisible. Boo es uno de los enemigos recurrentes en muchos juegos de Mario, especialmente en los de terror y en mansiones embrujadas.", "Boo","Invisibilidad"));
    datos.add(new Personaje(R.drawable.donkey_kong, "Donkey Kong es un gorila gigante y uno de los personajes más emblemáticos de la serie de Mario. Originalmente apareció como el antagonista en el juego Donkey Kong de 1981, donde secuestraba a la novia de Mario, Pauline. Con el tiempo, Donkey Kong se ha convertido en un héroe y protagonista en sus propias aventuras. Tiene una personalidad fuerte y a menudo se le representa como un protector de la selva y un defensor de su hogar, la Isla Donkey Kong.", "Donkey Kong","fuerza sobrehumana"));
    datos.add(new Personaje(R.drawable.diddy_kong, "Diddy Kong es el amigo y compañero de Donkey Kong, reconocido por su energía y espíritu aventurero. Es un pequeño simio con un gorro rojo y una camiseta a rayas, que refleja su personalidad juguetona. Diddy es conocido por ser un personaje valiente y leal, siempre dispuesto a ayudar a Donkey Kong en sus aventuras. A menudo es visto como un personaje más ágil y rápido en comparación con Donkey Kong.", "Diddy Kong","Agilidad y velocidad"));
   }

    public static List<Personaje> getDatos() {
        return datos;
    }
}
